//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AktiviteEntities : DbContext
    {
        public AktiviteEntities()
            : base("name=AktiviteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<View_Cagri_Test> View_Cagri_Test { get; set; }
        public virtual DbSet<View_Dashboard_Test> View_Dashboard_Test { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_2_Toplamlar> View_2_Toplamlar { get; set; }
        public virtual DbSet<View_2_Danisman> View_2_Danisman { get; set; }
        public virtual DbSet<View_2_Modul> View_2_Modul { get; set; }
    
        public virtual ObjectResult<S_Aktivite_Result> S_Aktivite(Nullable<int> iD, Nullable<int> danismanID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Aktivite_Result>("S_Aktivite", iDParameter, danismanIDParameter);
        }
    
        public virtual ObjectResult<S_Danisman_Result> S_Danisman(Nullable<int> iD, Nullable<System.Guid> userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Danisman_Result>("S_Danisman", iDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<S_Proje_Result> S_Proje(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Proje_Result>("S_Proje", iDParameter);
        }
    
        public virtual ObjectResult<S_ProjeDanisman_Result> S_ProjeDanisman(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_ProjeDanisman_Result>("S_ProjeDanisman", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Aktivite_Result> IUD_Aktivite(Nullable<int> iD, Nullable<System.DateTime> tarih, Nullable<int> projeID, Nullable<int> modulID, Nullable<int> danismanID, string aciklama, Nullable<decimal> saat, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var saatParameter = saat.HasValue ?
                new ObjectParameter("Saat", saat) :
                new ObjectParameter("Saat", typeof(decimal));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Aktivite_Result>("IUD_Aktivite", iDParameter, tarihParameter, projeIDParameter, modulIDParameter, danismanIDParameter, aciklamaParameter, saatParameter, silParameter);
        }
    
        public virtual ObjectResult<S_Planlama_Result> S_Planlama(Nullable<int> iD, Nullable<int> danismanID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Planlama_Result>("S_Planlama", iDParameter, danismanIDParameter);
        }
    
        public virtual ObjectResult<IUD_Planlama_Result> IUD_Planlama(Nullable<int> iD, Nullable<int> danismanID, Nullable<int> modulID, Nullable<int> projeID, Nullable<int> yukleniciID, Nullable<int> musteriID, Nullable<System.DateTime> tarih, Nullable<decimal> saat, string aciklama, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var yukleniciIDParameter = yukleniciID.HasValue ?
                new ObjectParameter("YukleniciID", yukleniciID) :
                new ObjectParameter("YukleniciID", typeof(int));
    
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var saatParameter = saat.HasValue ?
                new ObjectParameter("Saat", saat) :
                new ObjectParameter("Saat", typeof(decimal));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Planlama_Result>("IUD_Planlama", iDParameter, danismanIDParameter, modulIDParameter, projeIDParameter, yukleniciIDParameter, musteriIDParameter, tarihParameter, saatParameter, aciklamaParameter, silParameter);
        }
    
        public virtual ObjectResult<S_DanismaninProjeleri_Result> S_DanismaninProjeleri(Nullable<int> danismanID)
        {
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismaninProjeleri_Result>("S_DanismaninProjeleri", danismanIDParameter);
        }
    
        public virtual ObjectResult<S_MusteriLokasyon_Result> S_MusteriLokasyon(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MusteriLokasyon_Result>("S_MusteriLokasyon", iDParameter);
        }
    
        public virtual ObjectResult<S_Musteriler_Result> S_Musteriler(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Musteriler_Result>("S_Musteriler", iDParameter);
        }
    
        public virtual ObjectResult<S_Yukleniciler_Result> S_Yukleniciler(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Yukleniciler_Result>("S_Yukleniciler", iDParameter);
        }
    
        public virtual ObjectResult<S_ModulDanisman_Result> S_ModulDanisman(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_ModulDanisman_Result>("S_ModulDanisman", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Modul_Result> IUD_Modul(Nullable<int> iD, string aciklama, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Modul_Result>("IUD_Modul", iDParameter, aciklamaParameter, silParameter);
        }
    
        public virtual ObjectResult<S_Modul_Result> S_Modul(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Modul_Result>("S_Modul", iDParameter);
        }
    
        public virtual ObjectResult<IUD_DanismanTanimlari_Result> IUD_DanismanTanimlari(Nullable<int> iD, string aciklama, Nullable<bool> sil, string kullaniciID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var kullaniciIDParameter = kullaniciID != null ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_DanismanTanimlari_Result>("IUD_DanismanTanimlari", iDParameter, aciklamaParameter, silParameter, kullaniciIDParameter);
        }
    
        public virtual ObjectResult<S_DanismanTanimlari_Result> S_DanismanTanimlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismanTanimlari_Result>("S_DanismanTanimlari", iDParameter);
        }
    
        public virtual ObjectResult<IUD_YukleniciTanimlari_Result> IUD_YukleniciTanimlari(Nullable<int> iD, string aciklama, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_YukleniciTanimlari_Result>("IUD_YukleniciTanimlari", iDParameter, aciklamaParameter, silParameter);
        }
    
        public virtual ObjectResult<S_YukleniciTanimlari_Result> S_YukleniciTanimlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_YukleniciTanimlari_Result>("S_YukleniciTanimlari", iDParameter);
        }
    
        public virtual ObjectResult<IUD_MusteriTanimlari_Result> IUD_MusteriTanimlari(Nullable<int> iD, string aciklama, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_MusteriTanimlari_Result>("IUD_MusteriTanimlari", iDParameter, aciklamaParameter, silParameter);
        }
    
        public virtual ObjectResult<S_MusteriTanimlari_Result> S_MusteriTanimlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MusteriTanimlari_Result>("S_MusteriTanimlari", iDParameter);
        }
    
        public virtual ObjectResult<IUD_MusteriLokasyonTanimlari_Result> IUD_MusteriLokasyonTanimlari(Nullable<int> iD, string aciklama, Nullable<bool> sil, Nullable<int> musteriID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_MusteriLokasyonTanimlari_Result>("IUD_MusteriLokasyonTanimlari", iDParameter, aciklamaParameter, silParameter, musteriIDParameter);
        }
    
        public virtual ObjectResult<S_MusteriLokasyonTanimlari_Result> S_MusteriLokasyonTanimlari(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_MusteriLokasyonTanimlari_Result>("S_MusteriLokasyonTanimlari", iDParameter);
        }
    
        public virtual ObjectResult<S_ProjeModulDanisman_Result> S_ProjeModulDanisman(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_ProjeModulDanisman_Result>("S_ProjeModulDanisman", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Projeler_Result> IUD_Projeler(Nullable<int> iD, string aciklama, string kod, Nullable<int> musteriID, Nullable<int> musteriLokasyonID, Nullable<bool> yuklenici, Nullable<int> yukleniciID, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var kodParameter = kod != null ?
                new ObjectParameter("Kod", kod) :
                new ObjectParameter("Kod", typeof(string));
    
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            var musteriLokasyonIDParameter = musteriLokasyonID.HasValue ?
                new ObjectParameter("MusteriLokasyonID", musteriLokasyonID) :
                new ObjectParameter("MusteriLokasyonID", typeof(int));
    
            var yukleniciParameter = yuklenici.HasValue ?
                new ObjectParameter("Yuklenici", yuklenici) :
                new ObjectParameter("Yuklenici", typeof(bool));
    
            var yukleniciIDParameter = yukleniciID.HasValue ?
                new ObjectParameter("YukleniciID", yukleniciID) :
                new ObjectParameter("YukleniciID", typeof(int));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Projeler_Result>("IUD_Projeler", iDParameter, aciklamaParameter, kodParameter, musteriIDParameter, musteriLokasyonIDParameter, yukleniciParameter, yukleniciIDParameter, silParameter);
        }
    
        public virtual ObjectResult<IUD_ProjeDanisman_Result> IUD_ProjeDanisman(Nullable<int> iD, Nullable<int> projeID, Nullable<int> danismanID, Nullable<int> modulID, Nullable<decimal> fiyatGun, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var fiyatGunParameter = fiyatGun.HasValue ?
                new ObjectParameter("FiyatGun", fiyatGun) :
                new ObjectParameter("FiyatGun", typeof(decimal));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_ProjeDanisman_Result>("IUD_ProjeDanisman", iDParameter, projeIDParameter, danismanIDParameter, modulIDParameter, fiyatGunParameter, silParameter);
        }
    
        public virtual ObjectResult<S_DanismanModul_Result> S_DanismanModul(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismanModul_Result>("S_DanismanModul", iDParameter);
        }
    
        public virtual ObjectResult<IUD_DanismanModul_Result> IUD_DanismanModul(Nullable<int> iD, Nullable<int> danismanID, Nullable<int> modulID, Nullable<bool> sil)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_DanismanModul_Result>("IUD_DanismanModul", iDParameter, danismanIDParameter, modulIDParameter, silParameter);
        }
    
        public virtual ObjectResult<S_Ayarlar_Result> S_Ayarlar(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Ayarlar_Result>("S_Ayarlar", userIDParameter);
        }
    
        public virtual int IUD_Ayarlar(Nullable<System.Guid> userID, string theme)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var themeParameter = theme != null ?
                new ObjectParameter("Theme", theme) :
                new ObjectParameter("Theme", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IUD_Ayarlar", userIDParameter, themeParameter);
        }
    
        public virtual ObjectResult<S_DanismanModulTokenBox_Result> S_DanismanModulTokenBox(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismanModulTokenBox_Result>("S_DanismanModulTokenBox", iDParameter);
        }
    
        public virtual ObjectResult<IUD_ProjelerWizard_Result> IUD_ProjelerWizard(Nullable<int> iD, string aciklama, string kod, Nullable<int> musteriID, Nullable<int> musteriLokasyonID, Nullable<bool> yuklenici, Nullable<int> yukleniciID, Nullable<bool> sil, string danismanAdi)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var kodParameter = kod != null ?
                new ObjectParameter("Kod", kod) :
                new ObjectParameter("Kod", typeof(string));
    
            var musteriIDParameter = musteriID.HasValue ?
                new ObjectParameter("MusteriID", musteriID) :
                new ObjectParameter("MusteriID", typeof(int));
    
            var musteriLokasyonIDParameter = musteriLokasyonID.HasValue ?
                new ObjectParameter("MusteriLokasyonID", musteriLokasyonID) :
                new ObjectParameter("MusteriLokasyonID", typeof(int));
    
            var yukleniciParameter = yuklenici.HasValue ?
                new ObjectParameter("Yuklenici", yuklenici) :
                new ObjectParameter("Yuklenici", typeof(bool));
    
            var yukleniciIDParameter = yukleniciID.HasValue ?
                new ObjectParameter("YukleniciID", yukleniciID) :
                new ObjectParameter("YukleniciID", typeof(int));
    
            var silParameter = sil.HasValue ?
                new ObjectParameter("Sil", sil) :
                new ObjectParameter("Sil", typeof(bool));
    
            var danismanAdiParameter = danismanAdi != null ?
                new ObjectParameter("DanismanAdi", danismanAdi) :
                new ObjectParameter("DanismanAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_ProjelerWizard_Result>("IUD_ProjelerWizard", iDParameter, aciklamaParameter, kodParameter, musteriIDParameter, musteriLokasyonIDParameter, yukleniciParameter, yukleniciIDParameter, silParameter, danismanAdiParameter);
        }
    
        public virtual ObjectResult<S_ProjeDanismanlariGetir_Result> S_ProjeDanismanlariGetir(string danismanAdi)
        {
            var danismanAdiParameter = danismanAdi != null ?
                new ObjectParameter("DanismanAdi", danismanAdi) :
                new ObjectParameter("DanismanAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_ProjeDanismanlariGetir_Result>("S_ProjeDanismanlariGetir", danismanAdiParameter);
        }
    
        public virtual ObjectResult<S_Kullanici_Result> S_Kullanici(string kullaniciIDs)
        {
            var kullaniciIDsParameter = kullaniciIDs != null ?
                new ObjectParameter("KullaniciIDs", kullaniciIDs) :
                new ObjectParameter("KullaniciIDs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kullanici_Result>("S_Kullanici", kullaniciIDsParameter);
        }
    
        public virtual ObjectResult<IUD_Kullanici_Result> IUD_Kullanici(string userID, string kullaniciAdi, string eMail)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("KullaniciAdi", kullaniciAdi) :
                new ObjectParameter("KullaniciAdi", typeof(string));
    
            var eMailParameter = eMail != null ?
                new ObjectParameter("EMail", eMail) :
                new ObjectParameter("EMail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Kullanici_Result>("IUD_Kullanici", userIDParameter, kullaniciAdiParameter, eMailParameter);
        }
    
        public virtual ObjectResult<S_DanismanModulWizard_Result> S_DanismanModulWizard(string modulAdi, Nullable<int> danismanID)
        {
            var modulAdiParameter = modulAdi != null ?
                new ObjectParameter("ModulAdi", modulAdi) :
                new ObjectParameter("ModulAdi", typeof(string));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismanModulWizard_Result>("S_DanismanModulWizard", modulAdiParameter, danismanIDParameter);
        }
    
        public virtual ObjectResult<S_RaporProjeFinansDurumu_Result> S_RaporProjeFinansDurumu(Nullable<System.DateTime> basTar, Nullable<System.DateTime> bitTar, Nullable<System.Guid> kullaniciID)
        {
            var basTarParameter = basTar.HasValue ?
                new ObjectParameter("BasTar", basTar) :
                new ObjectParameter("BasTar", typeof(System.DateTime));
    
            var bitTarParameter = bitTar.HasValue ?
                new ObjectParameter("BitTar", bitTar) :
                new ObjectParameter("BitTar", typeof(System.DateTime));
    
            var kullaniciIDParameter = kullaniciID.HasValue ?
                new ObjectParameter("KullaniciID", kullaniciID) :
                new ObjectParameter("KullaniciID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_RaporProjeFinansDurumu_Result>("S_RaporProjeFinansDurumu", basTarParameter, bitTarParameter, kullaniciIDParameter);
        }
    
        public virtual ObjectResult<S_GridGroupCheckedDataSource_Result> S_GridGroupCheckedDataSource(string projeIDs, string danismanIDs, string modulIDs, Nullable<System.DateTime> basTar, Nullable<System.DateTime> bitTar, Nullable<System.Guid> userID)
        {
            var projeIDsParameter = projeIDs != null ?
                new ObjectParameter("ProjeIDs", projeIDs) :
                new ObjectParameter("ProjeIDs", typeof(string));
    
            var danismanIDsParameter = danismanIDs != null ?
                new ObjectParameter("DanismanIDs", danismanIDs) :
                new ObjectParameter("DanismanIDs", typeof(string));
    
            var modulIDsParameter = modulIDs != null ?
                new ObjectParameter("ModulIDs", modulIDs) :
                new ObjectParameter("ModulIDs", typeof(string));
    
            var basTarParameter = basTar.HasValue ?
                new ObjectParameter("BasTar", basTar) :
                new ObjectParameter("BasTar", typeof(System.DateTime));
    
            var bitTarParameter = bitTar.HasValue ?
                new ObjectParameter("BitTar", bitTar) :
                new ObjectParameter("BitTar", typeof(System.DateTime));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_GridGroupCheckedDataSource_Result>("S_GridGroupCheckedDataSource", projeIDsParameter, danismanIDsParameter, modulIDsParameter, basTarParameter, bitTarParameter, userIDParameter);
        }
    
        public virtual ObjectResult<S_Kisi_Result> S_Kisi(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kisi_Result>("S_Kisi", iDParameter);
        }
    
        public virtual ObjectResult<IUD_Mail_Result> IUD_Mail(Nullable<int> gonderenDanismanID, string gonderilenMailAdresi, string hTML, Nullable<bool> durum, Nullable<System.DateTime> gonderimTarihi, string gonderenMailAdresi, string konu, string promotionName, Nullable<bool> ekteDosya, string ekteDosyaYolu)
        {
            var gonderenDanismanIDParameter = gonderenDanismanID.HasValue ?
                new ObjectParameter("GonderenDanismanID", gonderenDanismanID) :
                new ObjectParameter("GonderenDanismanID", typeof(int));
    
            var gonderilenMailAdresiParameter = gonderilenMailAdresi != null ?
                new ObjectParameter("GonderilenMailAdresi", gonderilenMailAdresi) :
                new ObjectParameter("GonderilenMailAdresi", typeof(string));
    
            var hTMLParameter = hTML != null ?
                new ObjectParameter("HTML", hTML) :
                new ObjectParameter("HTML", typeof(string));
    
            var durumParameter = durum.HasValue ?
                new ObjectParameter("Durum", durum) :
                new ObjectParameter("Durum", typeof(bool));
    
            var gonderimTarihiParameter = gonderimTarihi.HasValue ?
                new ObjectParameter("GonderimTarihi", gonderimTarihi) :
                new ObjectParameter("GonderimTarihi", typeof(System.DateTime));
    
            var gonderenMailAdresiParameter = gonderenMailAdresi != null ?
                new ObjectParameter("GonderenMailAdresi", gonderenMailAdresi) :
                new ObjectParameter("GonderenMailAdresi", typeof(string));
    
            var konuParameter = konu != null ?
                new ObjectParameter("Konu", konu) :
                new ObjectParameter("Konu", typeof(string));
    
            var promotionNameParameter = promotionName != null ?
                new ObjectParameter("PromotionName", promotionName) :
                new ObjectParameter("PromotionName", typeof(string));
    
            var ekteDosyaParameter = ekteDosya.HasValue ?
                new ObjectParameter("EkteDosya", ekteDosya) :
                new ObjectParameter("EkteDosya", typeof(bool));
    
            var ekteDosyaYoluParameter = ekteDosyaYolu != null ?
                new ObjectParameter("EkteDosyaYolu", ekteDosyaYolu) :
                new ObjectParameter("EkteDosyaYolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IUD_Mail_Result>("IUD_Mail", gonderenDanismanIDParameter, gonderilenMailAdresiParameter, hTMLParameter, durumParameter, gonderimTarihiParameter, gonderenMailAdresiParameter, konuParameter, promotionNameParameter, ekteDosyaParameter, ekteDosyaYoluParameter);
        }
    
        public virtual ObjectResult<S_KullaniciYetkileri_Result> S_KullaniciYetkileri(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_KullaniciYetkileri_Result>("S_KullaniciYetkileri", userIDParameter);
        }
    
        public virtual ObjectResult<S_CagriIstek_Result> S_CagriIstek(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriIstek_Result>("S_CagriIstek", iDParameter);
        }
    
        public virtual ObjectResult<S_Cagri_Result> S_Cagri(Nullable<int> iD, Nullable<int> danismanID, Nullable<int> cagriDurumu)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var cagriDurumuParameter = cagriDurumu.HasValue ?
                new ObjectParameter("CagriDurumu", cagriDurumu) :
                new ObjectParameter("CagriDurumu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Cagri_Result>("S_Cagri", iDParameter, danismanIDParameter, cagriDurumuParameter);
        }
    
        public virtual int I_CagriIstekExcelZorlu(string path)
        {
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_CagriIstekExcelZorlu", pathParameter);
        }
    
        public virtual int IUD_CagriYonlendir(string cagriIstekID, Nullable<int> danismanID, string modulID)
        {
            var cagriIstekIDParameter = cagriIstekID != null ?
                new ObjectParameter("CagriIstekID", cagriIstekID) :
                new ObjectParameter("CagriIstekID", typeof(string));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var modulIDParameter = modulID != null ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IUD_CagriYonlendir", cagriIstekIDParameter, danismanIDParameter, modulIDParameter);
        }
    
        public virtual int I_CagriyaBasla(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_CagriyaBasla", iDParameter);
        }
    
        public virtual int I_CagriYonlendir(Nullable<int> cagriID, Nullable<int> danismanID)
        {
            var cagriIDParameter = cagriID.HasValue ?
                new ObjectParameter("CagriID", cagriID) :
                new ObjectParameter("CagriID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_CagriYonlendir", cagriIDParameter, danismanIDParameter);
        }
    
        public virtual int IUD_CagriSonucGirOnayaGonder(Nullable<int> cagriID, Nullable<System.DateTime> baslangicTarihSaat, Nullable<System.DateTime> bitisTarihSaat, string sonucAciklama, Nullable<decimal> toplamCozumSuresi, Nullable<int> danismanID)
        {
            var cagriIDParameter = cagriID.HasValue ?
                new ObjectParameter("CagriID", cagriID) :
                new ObjectParameter("CagriID", typeof(int));
    
            var baslangicTarihSaatParameter = baslangicTarihSaat.HasValue ?
                new ObjectParameter("BaslangicTarihSaat", baslangicTarihSaat) :
                new ObjectParameter("BaslangicTarihSaat", typeof(System.DateTime));
    
            var bitisTarihSaatParameter = bitisTarihSaat.HasValue ?
                new ObjectParameter("BitisTarihSaat", bitisTarihSaat) :
                new ObjectParameter("BitisTarihSaat", typeof(System.DateTime));
    
            var sonucAciklamaParameter = sonucAciklama != null ?
                new ObjectParameter("SonucAciklama", sonucAciklama) :
                new ObjectParameter("SonucAciklama", typeof(string));
    
            var toplamCozumSuresiParameter = toplamCozumSuresi.HasValue ?
                new ObjectParameter("ToplamCozumSuresi", toplamCozumSuresi) :
                new ObjectParameter("ToplamCozumSuresi", typeof(decimal));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IUD_CagriSonucGirOnayaGonder", cagriIDParameter, baslangicTarihSaatParameter, bitisTarihSaatParameter, sonucAciklamaParameter, toplamCozumSuresiParameter, danismanIDParameter);
        }
    
        public virtual int U_CagriDurumuGuncelle(Nullable<int> cagriID, Nullable<int> durumID)
        {
            var cagriIDParameter = cagriID.HasValue ?
                new ObjectParameter("CagriID", cagriID) :
                new ObjectParameter("CagriID", typeof(int));
    
            var durumIDParameter = durumID.HasValue ?
                new ObjectParameter("DurumID", durumID) :
                new ObjectParameter("DurumID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_CagriDurumuGuncelle", cagriIDParameter, durumIDParameter);
        }
    
        public virtual int IU_CagriyiYakala(Nullable<int> cagriIstekID, Nullable<int> danismanID)
        {
            var cagriIstekIDParameter = cagriIstekID.HasValue ?
                new ObjectParameter("CagriIstekID", cagriIstekID) :
                new ObjectParameter("CagriIstekID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IU_CagriyiYakala", cagriIstekIDParameter, danismanIDParameter);
        }
    
        public virtual ObjectResult<S_CagriSonuc_Result> S_CagriSonuc(Nullable<int> cagriID, Nullable<int> danismanID)
        {
            var cagriIDParameter = cagriID.HasValue ?
                new ObjectParameter("CagriID", cagriID) :
                new ObjectParameter("CagriID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriSonuc_Result>("S_CagriSonuc", cagriIDParameter, danismanIDParameter);
        }
    
        public virtual ObjectResult<S_DanismaninYetkiliProjeleri_Result> S_DanismaninYetkiliProjeleri(Nullable<int> danismanID)
        {
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismaninYetkiliProjeleri_Result>("S_DanismaninYetkiliProjeleri", danismanIDParameter);
        }
    
        public virtual ObjectResult<S_DanismaninProjeModulleri_Result> S_DanismaninProjeModulleri(Nullable<int> danismanID)
        {
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_DanismaninProjeModulleri_Result>("S_DanismaninProjeModulleri", danismanIDParameter);
        }
    
        public virtual ObjectResult<S_CagriModul_Result> S_CagriModul(Nullable<int> cagriID)
        {
            var cagriIDParameter = cagriID.HasValue ?
                new ObjectParameter("CagriID", cagriID) :
                new ObjectParameter("CagriID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriModul_Result>("S_CagriModul", cagriIDParameter);
        }
    
        public virtual ObjectResult<S_CagriTumu_Result> S_CagriTumu(Nullable<int> cagriDurumu)
        {
            var cagriDurumuParameter = cagriDurumu.HasValue ?
                new ObjectParameter("CagriDurumu", cagriDurumu) :
                new ObjectParameter("CagriDurumu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriTumu_Result>("S_CagriTumu", cagriDurumuParameter);
        }
    
        public virtual int IUD_Istek(string extTicNo, string altTicNo, string ilgKisi, Nullable<System.DateTime> istekTar, string sirAdi, string aciklama, Nullable<System.Guid> userId, Nullable<int> onemDerecesi)
        {
            var extTicNoParameter = extTicNo != null ?
                new ObjectParameter("ExtTicNo", extTicNo) :
                new ObjectParameter("ExtTicNo", typeof(string));
    
            var altTicNoParameter = altTicNo != null ?
                new ObjectParameter("AltTicNo", altTicNo) :
                new ObjectParameter("AltTicNo", typeof(string));
    
            var ilgKisiParameter = ilgKisi != null ?
                new ObjectParameter("IlgKisi", ilgKisi) :
                new ObjectParameter("IlgKisi", typeof(string));
    
            var istekTarParameter = istekTar.HasValue ?
                new ObjectParameter("IstekTar", istekTar) :
                new ObjectParameter("IstekTar", typeof(System.DateTime));
    
            var sirAdiParameter = sirAdi != null ?
                new ObjectParameter("SirAdi", sirAdi) :
                new ObjectParameter("SirAdi", typeof(string));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(System.Guid));
    
            var onemDerecesiParameter = onemDerecesi.HasValue ?
                new ObjectParameter("OnemDerecesi", onemDerecesi) :
                new ObjectParameter("OnemDerecesi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IUD_Istek", extTicNoParameter, altTicNoParameter, ilgKisiParameter, istekTarParameter, sirAdiParameter, aciklamaParameter, userIdParameter, onemDerecesiParameter);
        }
    
        public virtual ObjectResult<S_AktiviteDanismaninProjeleri_Result> S_AktiviteDanismaninProjeleri(Nullable<int> danismanID)
        {
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktiviteDanismaninProjeleri_Result>("S_AktiviteDanismaninProjeleri", danismanIDParameter);
        }
    
        public virtual ObjectResult<S_AktivteGirisBilgileriYenileme_Result> S_AktivteGirisBilgileriYenileme(Nullable<int> projeID, Nullable<int> danismanID, Nullable<int> modulID)
        {
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var danismanIDParameter = danismanID.HasValue ?
                new ObjectParameter("DanismanID", danismanID) :
                new ObjectParameter("DanismanID", typeof(int));
    
            var modulIDParameter = modulID.HasValue ?
                new ObjectParameter("ModulID", modulID) :
                new ObjectParameter("ModulID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_AktivteGirisBilgileriYenileme_Result>("S_AktivteGirisBilgileriYenileme", projeIDParameter, danismanIDParameter, modulIDParameter);
        }
    
        public virtual ObjectResult<R_Aktiviteler_Result> R_Aktiviteler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_Aktiviteler_Result>("R_Aktiviteler");
        }
    
        public virtual ObjectResult<S_GridGroupCheckedDataSourceAktiviteRaporu_Result> S_GridGroupCheckedDataSourceAktiviteRaporu(string aktiviteIDs)
        {
            var aktiviteIDsParameter = aktiviteIDs != null ?
                new ObjectParameter("AktiviteIDs", aktiviteIDs) :
                new ObjectParameter("AktiviteIDs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_GridGroupCheckedDataSourceAktiviteRaporu_Result>("S_GridGroupCheckedDataSourceAktiviteRaporu", aktiviteIDsParameter);
        }
    
        public virtual ObjectResult<S_Tip_Result> S_Tip(Nullable<int> ayirac)
        {
            var ayiracParameter = ayirac.HasValue ?
                new ObjectParameter("Ayirac", ayirac) :
                new ObjectParameter("Ayirac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Tip_Result>("S_Tip", ayiracParameter);
        }
    
        public virtual ObjectResult<S_Destec_GonderilecekMailAdresleri_Result> S_Destec_GonderilecekMailAdresleri(Nullable<int> islemTipi, Nullable<System.Guid> userID, Nullable<System.Guid> sirketID, Nullable<int> kayitID)
        {
            var islemTipiParameter = islemTipi.HasValue ?
                new ObjectParameter("IslemTipi", islemTipi) :
                new ObjectParameter("IslemTipi", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            var sirketIDParameter = sirketID.HasValue ?
                new ObjectParameter("SirketID", sirketID) :
                new ObjectParameter("SirketID", typeof(System.Guid));
    
            var kayitIDParameter = kayitID.HasValue ?
                new ObjectParameter("KayitID", kayitID) :
                new ObjectParameter("KayitID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_GonderilecekMailAdresleri_Result>("S_Destec_GonderilecekMailAdresleri", islemTipiParameter, userIDParameter, sirketIDParameter, kayitIDParameter);
        }
    
        public virtual ObjectResult<S_Destec_KullaniciIDVer_Result> S_Destec_KullaniciIDVer(string kullaniciAdi)
        {
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("KullaniciAdi", kullaniciAdi) :
                new ObjectParameter("KullaniciAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_KullaniciIDVer_Result>("S_Destec_KullaniciIDVer", kullaniciAdiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> I_Mail(Nullable<int> gonderenDanismanID, string gonderilenMailAdresi, string hTML, Nullable<bool> durum, Nullable<System.DateTime> gonderimTarihi, string gonderenMailAdresi, string konu, string promotionName, Nullable<bool> ekteDosya, string ekteDosyaYolu)
        {
            var gonderenDanismanIDParameter = gonderenDanismanID.HasValue ?
                new ObjectParameter("GonderenDanismanID", gonderenDanismanID) :
                new ObjectParameter("GonderenDanismanID", typeof(int));
    
            var gonderilenMailAdresiParameter = gonderilenMailAdresi != null ?
                new ObjectParameter("GonderilenMailAdresi", gonderilenMailAdresi) :
                new ObjectParameter("GonderilenMailAdresi", typeof(string));
    
            var hTMLParameter = hTML != null ?
                new ObjectParameter("HTML", hTML) :
                new ObjectParameter("HTML", typeof(string));
    
            var durumParameter = durum.HasValue ?
                new ObjectParameter("Durum", durum) :
                new ObjectParameter("Durum", typeof(bool));
    
            var gonderimTarihiParameter = gonderimTarihi.HasValue ?
                new ObjectParameter("GonderimTarihi", gonderimTarihi) :
                new ObjectParameter("GonderimTarihi", typeof(System.DateTime));
    
            var gonderenMailAdresiParameter = gonderenMailAdresi != null ?
                new ObjectParameter("GonderenMailAdresi", gonderenMailAdresi) :
                new ObjectParameter("GonderenMailAdresi", typeof(string));
    
            var konuParameter = konu != null ?
                new ObjectParameter("Konu", konu) :
                new ObjectParameter("Konu", typeof(string));
    
            var promotionNameParameter = promotionName != null ?
                new ObjectParameter("PromotionName", promotionName) :
                new ObjectParameter("PromotionName", typeof(string));
    
            var ekteDosyaParameter = ekteDosya.HasValue ?
                new ObjectParameter("EkteDosya", ekteDosya) :
                new ObjectParameter("EkteDosya", typeof(bool));
    
            var ekteDosyaYoluParameter = ekteDosyaYolu != null ?
                new ObjectParameter("EkteDosyaYolu", ekteDosyaYolu) :
                new ObjectParameter("EkteDosyaYolu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("I_Mail", gonderenDanismanIDParameter, gonderilenMailAdresiParameter, hTMLParameter, durumParameter, gonderimTarihiParameter, gonderenMailAdresiParameter, konuParameter, promotionNameParameter, ekteDosyaParameter, ekteDosyaYoluParameter);
        }
    
        public virtual ObjectResult<S_CagriIstekOnaylananlar_Result> S_CagriIstekOnaylananlar(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_CagriIstekOnaylananlar_Result>("S_CagriIstekOnaylananlar", iDParameter);
        }
    
        public virtual ObjectResult<S_Destec_SirketIDVer_Result> S_Destec_SirketIDVer(string sirketAdi)
        {
            var sirketAdiParameter = sirketAdi != null ?
                new ObjectParameter("SirketAdi", sirketAdi) :
                new ObjectParameter("SirketAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Destec_SirketIDVer_Result>("S_Destec_SirketIDVer", sirketAdiParameter);
        }
    
        public virtual ObjectResult<R_AktiviteDestek_Result> R_AktiviteDestek(Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_AktiviteDestek_Result>("R_AktiviteDestek", baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual ObjectResult<R_AktiviteDestekDetail_Result> R_AktiviteDestekDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_AktiviteDestekDetail_Result>("R_AktiviteDestekDetail");
        }
    
        public virtual ObjectResult<R_AktiviteDestek2_Result> R_AktiviteDestek2(Nullable<System.DateTime> baslangicTarihi, Nullable<System.DateTime> bitisTarihi)
        {
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(System.DateTime));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<R_AktiviteDestek2_Result>("R_AktiviteDestek2", baslangicTarihiParameter, bitisTarihiParameter);
        }
    
        public virtual ObjectResult<S_ProjeyeSirketBagla_Result> S_ProjeyeSirketBagla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_ProjeyeSirketBagla_Result>("S_ProjeyeSirketBagla");
        }
    
        public virtual ObjectResult<S_Sirket_Result> S_Sirket()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Sirket_Result>("S_Sirket");
        }
    
        public virtual int D_ProjeyeSirketBagla(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("D_ProjeyeSirketBagla", iDParameter);
        }
    
        public virtual int I_ProjeyeSirketBagla(Nullable<int> projeID, Nullable<System.Guid> sirketId)
        {
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("SirketId", sirketId) :
                new ObjectParameter("SirketId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("I_ProjeyeSirketBagla", projeIDParameter, sirketIdParameter);
        }
    
        public virtual int U_ProjeyeSirketBagla(Nullable<int> iD, Nullable<int> projeID, Nullable<System.Guid> sirketId)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var projeIDParameter = projeID.HasValue ?
                new ObjectParameter("ProjeID", projeID) :
                new ObjectParameter("ProjeID", typeof(int));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("SirketId", sirketId) :
                new ObjectParameter("SirketId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("U_ProjeyeSirketBagla", iDParameter, projeIDParameter, sirketIdParameter);
        }
    }
}
