//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2_Toplamlar
    {
        public int IstekAsamasinda { get; set; }
        public int CagriyaDonusmus { get; set; }
        public Nullable<int> AcikCagrilar { get; set; }
        public Nullable<int> KapanmisCagrilar { get; set; }
        public Nullable<int> BekleyenCagrilar { get; set; }
        public Nullable<int> OnayBekleyenCagrilar { get; set; }
    }
}
