//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Cagri_Test
    {
        public int ID { get; set; }
        public int CagriIstekID { get; set; }
        public Nullable<System.DateTime> CagriIstekKayitTarihiSaati { get; set; }
        public string InternalTicketNumber { get; set; }
        public string ExternalTicketNumber { get; set; }
        public string AlternativeTicketNumber { get; set; }
        public string IstekSahibiAdiSoyadi { get; set; }
        public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
        public string IstekSirketAdi { get; set; }
        public string IstekSirketKodu { get; set; }
        public string IstekAciklama { get; set; }
        public System.DateTime SistemKayitTarihiSaati { get; set; }
        public int AtananDanismanID { get; set; }
        public int YonlendirilenDanismanID { get; set; }
        public Nullable<System.DateTime> YonlendirilenDanismanTarihSaati { get; set; }
        public Nullable<System.Guid> KayitOlusturanKullaniciID { get; set; }
        public Nullable<System.Guid> KayitDegistirenKullaniciID { get; set; }
        public int CagriDurumu_TipID1 { get; set; }
        public Nullable<int> T_CagriSonucID { get; set; }
        public Nullable<int> CagriID { get; set; }
        public Nullable<bool> CagriKapatildi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihSaat { get; set; }
        public Nullable<System.DateTime> BitisTarihSaat { get; set; }
        public string SonucAciklama { get; set; }
        public Nullable<int> ToplamCozumSuresiSaat { get; set; }
        public Nullable<System.DateTime> CagriSonucTarih { get; set; }
        public Nullable<int> KayitOlusturanDanismanID { get; set; }
        public Nullable<int> KayitDegistirenDanismanID { get; set; }
        public Nullable<System.DateTime> SistemDegistirmeTarihSaati { get; set; }
        public Nullable<int> CagriModulID { get; set; }
        public Nullable<int> CagriModulCagriID { get; set; }
        public Nullable<int> ModulID { get; set; }
        public Nullable<int> T_ModulID { get; set; }
        public string ModulAdi { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> CagriAktiviteID { get; set; }
        public Nullable<int> CagriSonucID { get; set; }
        public Nullable<int> AktiviteID { get; set; }
        public Nullable<System.DateTime> CagriAktiviteTarih { get; set; }
        public Nullable<int> Expr8 { get; set; }
    }
}
