//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Dashboard_Test
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> ProjeID { get; set; }
        public Nullable<int> ModulID { get; set; }
        public Nullable<int> DanismanID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Saat { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string ProjeAdi { get; set; }
        public string Kod { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> MusteriLokasyonID { get; set; }
        public Nullable<bool> Yuklenici { get; set; }
        public Nullable<int> YukleniciID { get; set; }
        public Nullable<bool> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public string ModulAdi { get; set; }
        public Nullable<bool> Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public string DanismanAdi { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<bool> Expr9 { get; set; }
    }
}
