//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2_Danisman
    {
        public string DanismanAdi { get; set; }
        public int AcikCagrilar { get; set; }
        public int KapanmisCagrilar { get; set; }
        public int BekleyenCagrilar { get; set; }
        public int OnayBekleyenCagrilar { get; set; }
    }
}
