//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXAktivite2
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int IstekID { get; set; }
        public string ExternalTicketNumber { get; set; }
        public string IstekSahibiAdiSoyadi { get; set; }
        public Nullable<System.DateTime> IstekTarihiSaati { get; set; }
        public string IstekSirketAdi { get; set; }
        public string IstekAciklama { get; set; }
        public System.DateTime IstekSistemKayitTarihSaati { get; set; }
        public bool CagriyaDonus { get; set; }
        public Nullable<int> CagriID { get; set; }
        public string InternalTicketNumber { get; set; }
        public Nullable<System.DateTime> CagriSistemKayitTarihSaati { get; set; }
        public Nullable<int> CagriDurumu_TipID1 { get; set; }
        public string CagriAtananDanismanAdi { get; set; }
        public string CagrininModulu { get; set; }
        public Nullable<bool> CagriKapatildi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihSaat { get; set; }
        public Nullable<System.DateTime> BitisTarihSaat { get; set; }
        public string SonucAciklama { get; set; }
        public Nullable<int> ToplamCozumSuresiSaat { get; set; }
        public Nullable<System.DateTime> SonucSistemKayitTarihSaati { get; set; }
        public string SonucDanismanAdi { get; set; }
    }
}
